version: "3"

services:
  node-app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "7007:7007"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-front-end-r7-test
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
